"""The single definition of a legal truck->load dispatch.

Every policy in this project is scored against this one function, so a
"constraint-aware" policy and the naive baseline cannot be judged by different
rules. Three hard constraints:

  C1 trailer compatibility        (models.can_haul)
  C2 pickup time window           truck must arrive by pickup_close_min
  C3 hours of service             deadhead drive + shipper wait + pickup
                                  overhead + LOADED drive must all fit inside
                                  the duty day

C3 has been wrong twice, in the same direction, and both corrections are
recorded here rather than in a footnote:

  round-1 finding D1  -- it charged only the deadhead leg. Judged by the rule
                         as it now stands, 22.53% of the winning policy's
                         dispatches under that rule were illegal (worst duty
                         day 23.78 h). Fixed by charging the loaded leg.
  round-2 finding
       DOMAIN-01      -- it still charged no time for waiting at the shipper for
                         the pickup window to open, which is on-duty
                         not-driving. Judged by the rule as it now stands,
                         42.79% of the winning policy's dispatches under that
                         rule were illegal (worst duty day 24.45 h -- worse than
                         the defect D1 fixed). Fixed by charging the wait.

Both figures are regenerated by tests/test_hos_binds_the_whole_duty_day.py, so
they are measurements this suite keeps honest, not sentences in a docstring.
"""

from __future__ import annotations

from dataclasses import dataclass

from .geo import road_km
from .hos import drive_minutes, hos_ok
from .models import Load, Truck, can_haul


@dataclass(frozen=True, slots=True)
class Leg:
    deadhead_km: float
    drive_min: int
    arrive_min: int
    #: Minutes the truck stands at the shipper before the pickup window opens.
    #: On-duty not-driving; see roadstar.hos. Zero if the truck arrives inside
    #: or after the window.
    wait_min: int


def loaded_drive_minutes(load: Load) -> int:
    """Driving minutes of the loaded leg itself, origin to destination."""
    return drive_minutes(load.loaded_km)


def leg(truck: Truck, load: Load) -> Leg:
    """The empty repositioning leg from where the truck sits to the pickup."""
    km = road_km(truck.at, load.origin)
    dm = drive_minutes(km)
    arrive = truck.free_from_min + dm
    return Leg(
        deadhead_km=km,
        drive_min=dm,
        arrive_min=arrive,
        wait_min=max(0, load.pickup_open_min - arrive),
    )


def violations(truck: Truck, load: Load) -> tuple[str, ...]:
    """Every hard constraint this pairing breaks. Empty tuple == feasible."""
    bad: list[str] = []
    if not can_haul(truck.trailer, load.requires):
        bad.append("C1_trailer")
    lg = leg(truck, load)
    if lg.arrive_min > load.pickup_close_min:
        bad.append("C2_window")
    added_drive = lg.drive_min + loaded_drive_minutes(load)
    if not hos_ok(
        truck.drive_used_min,
        truck.onduty_used_min,
        added_drive,
        wait_min=lg.wait_min,
    ):
        bad.append("C3_hos")
    return tuple(bad)


def is_feasible(truck: Truck, load: Load) -> bool:
    return not violations(truck, load)
